MvcMovie/Models/Actors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcMovie.Models
{
    public class Actors
    {
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 2)]
        [Display(Name = "First Name")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(60, MinimumLength = 2)]
        [Required]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }

        [RegularExpression(@"^[a-zA-Z\s]*$", ErrorMessage = "Must only use letters or spaces")]
        [Required]
        [StringLength(30)]
        public string Skill { get; set; }

        [Display(Name = "Birth Place")]
        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$", ErrorMessage = "Must Begin with uppercase letter")]
        [StringLength(30)]
        public string Birthplace { get; set; }
        // 1
        [Range(0, int.MaxValue, ErrorMessage = "Can't be negative")]
        [Display(Name = "Net Worth")]
        [DataType(DataType.Currency)]
        public decimal Networth { get; set; }
    }
}

MvcMovie/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class ActorsController : Controller
    {
        private readonly MvcMovieContext _context;

        public ActorsController(MvcMovieContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string skill, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> skillquery = from m in _context.Actors
                                            orderby m.Skill
                                            select m.Skill;

            var actors = from m in _context.Actors
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                actors = actors.Where(s => s.FirstName.Contains(searchString) || s.LastName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(skill))
            {
                actors = actors.Where(x => x.Skill == skill);
            }

            var actorSkillVM = new ActorSkillViewModel
            {
                skills = new SelectList(await skillquery.Distinct().ToListAsync()),
                actors = await actors.ToListAsync()
            };

            return View(actorSkillVM);
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actors = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actors == null)
            {
                return NotFound();
            }

            return View(actors);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Birthday,Birthplace,Skill,Networth")] Actors actors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actors);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actors = await _context.Actors.FindAsync(id);
            if (actors == null)
            {
                return NotFound();
            }
            return View(actors);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Birthday,Skill,Birthplace,Networth")] Actors actors)
        {
            if (id != actors.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorsExists(actors.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actors);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actors = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actors == null)
            {
                return NotFound();
            }

            return View(actors);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actors = await _context.Actors.FindAsync(id);
            _context.Actors.Remove(actors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorsExists(int id)
        {
            return _context.Actors.Any(e => e.Id == id);
        }
    }
}

MvcMovie/Views/Actors/Create.cshtml
@model MvcMovie.Models.Actors

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Actors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skill" class="control-label"></label>
                <input asp-for="Skill" class="form-control" />
                <span asp-validation-for="Skill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthplace" class="control-label"></label>
                <input asp-for="Birthplace" class="form-control" />
                <span asp-validation-for="Birthplace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Networth" class="control-label"></label>
                <input asp-for="Networth" class="form-control" />
                <span asp-validation-for="Networth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/Views/Actors/Delete.cshtml
@model MvcMovie.Models.Actors

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actors</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Skill)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Skill)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Birthplace)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthplace)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Networth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Networth)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcMovie/Views/Actors/Details.cshtml
@model MvcMovie.Models.Actors

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Actors</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Skill)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Skill)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Birthplace)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Birthplace)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Networth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Networth)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcMovie/Views/Actors/Edit.cshtml
@model MvcMovie.Models.Actors

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Actors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skill" class="control-label"></label>
                <input asp-for="Skill" class="form-control" />
                <span asp-validation-for="Skill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthplace" class="control-label"></label>
                <input asp-for="Birthplace" class="form-control" />
                <span asp-validation-for="Birthplace" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Networth" class="control-label"></label>
                <input asp-for="Networth" class="form-control" />
                <span asp-validation-for="Networth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/Views/Actors/Index.cshtml
@model MvcMovie.Models.ActorSkillViewModel


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Actors" asp-action="Index" method="get">
    <p>
        <select asp-for="skill" asp-items="Model.skills">
            <option value="">All</option>
        </select>

        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].Skill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].Networth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.actors[0].Birthplace)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.actors)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Skill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Networth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthplace)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>